import { TributePageData } from './types';

export const demoTributeData: TributePageData = {
  employee: {
    id: 'demo-employee-1',
    name: 'Michael Scott',
    email: 'michael.scott@dundermifflin.com',
    date_of_birth: '1965-03-15',
    start_date: '1992-04-06',
    department: 'Dunder Mifflin Scranton',
  },
  celebration: {
    id: 'demo-celebration-1',
    employee_id: 'demo-employee-1',
    type: 'birthday',
    title: 'Gratulerer med dagen, Michael!',
    status: 'published',
    share_token: 'demo12345',
  },
  giftCard: {
    brand: 'ODEON Kino',
    value: '500 kr',
    message: 'Nyt en filmkveld på oss!',
  },
  contributors: [
    'Jim Halpert',
    'Pam Beesly',
    'Dwight Schrute',
    'Angela Martin',
    'Kevin Malone',
  ],
  questions: [
    {
      id: 'demo-q1',
      celebration_id: 'demo-celebration-1',
      text: 'Hva setter du mest pris på med Michael?',
      sort_order: 0,
      allow_image: false,
      is_required: true,
      responses: [
        {
          id: 'demo-r1',
          question_id: 'demo-q1',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Jim Halpert',
          text_response: 'Michael sier mye rart — virkelig mye rart — men innimellom kommer han med noe som faktisk er geniale livsråd. Man vet bare aldri når det kommer, og det er kanskje det som gjør det så bra.',
          image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
        },
        {
          id: 'demo-r2',
          question_id: 'demo-q1',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Pam Beesly',
          text_response: 'Michael tror på folk, selv når de ikke tror på seg selv. Han så noe i meg lenge før jeg turte å se det selv. Det er en sjelden egenskap, og jeg er takknemlig for det.',
        },
        {
          id: 'demo-r3',
          question_id: 'demo-q1',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Dwight Schrute',
          text_response: 'Michael Scott er den beste regionalsjefen i hele Dunder Mifflin-historien. Hans lederskap er uten sidestykke. Jeg ville fulgt ham inn i kamp uten å nøle.',
        },
        {
          id: 'demo-r4',
          question_id: 'demo-q1',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Angela Martin',
          text_response: 'Selv om metodene hans er... uortodokse, må jeg innrømme at Michael har arrangert noen minnerike kontorbegivenheter. Dundies-seremonien var faktisk ganske hyggelig.',
        },
        {
          id: 'demo-r5',
          question_id: 'demo-q1',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Kevin Malone',
          text_response: 'Michael deler alltid snacksene sine med meg. Og han ler av vitsene mine. Det er det ikke alle som gjør. Han er en god mann.',
          image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
        },
      ],
    },
    {
      id: 'demo-q2',
      celebration_id: 'demo-celebration-1',
      text: 'Del et favorittminne med Michael',
      sort_order: 1,
      allow_image: false,
      is_required: false,
      responses: [
        {
          id: 'demo-r6',
          question_id: 'demo-q2',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Jim Halpert',
          text_response: 'The Dundies. Hvert eneste år insisterer Michael på å holde sin egen prisutdeling på Chili\'s. Det er kaos, det er pinlig, og det er det beste arrangementet vi har. Jeg mener det faktisk.',
        },
        {
          id: 'demo-r7',
          question_id: 'demo-q2',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Pam Beesly',
          text_response: 'Da Michael sa "That\'s what she said" midt i en seriøs presentasjon for en viktig klient. Klienten lo så hardt at de signerte avtalen på stedet. Michael kalte det strategi. Det var det nok ikke.',
          image_url: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80',
        },
        {
          id: 'demo-r8',
          question_id: 'demo-q2',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Dwight Schrute',
          text_response: 'Paintball-teambuilding i skogen bak lageret. Michael og jeg var på samme lag, og vi vant. Det var som en militæroperasjon — perfekt utført. Ingen skader. Nesten ingen skader.',
          image_url: 'https://images.unsplash.com/photo-1472745942893-4b9f730c7668?w=800&q=80',
        },
      ],
    },
    {
      id: 'demo-q3',
      celebration_id: 'demo-celebration-1',
      text: 'Hva ønsker du Michael for det kommende året?',
      sort_order: 2,
      allow_image: false,
      is_required: false,
      responses: [
        {
          id: 'demo-r9',
          question_id: 'demo-q3',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Kevin Malone',
          text_response: 'Flere pizzafester. Og kanskje taco-tirsdager. Og is om fredagene. Egentlig bare mer mat generelt.',
        },
        {
          id: 'demo-r10',
          question_id: 'demo-q3',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Angela Martin',
          text_response: 'Et roligere og mer organisert år. Kanskje litt færre spontane fester og litt mer fokus på budsjettet. Men gratulerer med dagen, Michael.',
        },
        {
          id: 'demo-r11',
          question_id: 'demo-q3',
          celebration_id: 'demo-celebration-1',
          contributor_name: 'Pam Beesly',
          text_response: 'Jeg ønsker Michael et år der han følger drømmene sine — alle sammen. Verden fortjener mer av hans entusiasme og varme. Gratulerer med dagen, Michael!',
        },
      ],
    },
  ],
};
